services:
  bot:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    env_file: .env
    ports:
      - "8080:8080"
    command: bash -lc "pip install --no-cache-dir -r requirements.txt && python run.py"
    restart: unless-stopped
